Add settings.py의 products App 설정,backend README.md,products models.py
wecode-bootcamp-korea/10-RonWesely-backend pull request #3
Opened 2020-07-22 12:31 UTC by sincerity10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- products App 모델링 리뷰 후, models.py 작성완료
- README.md 추가
		 
## 수정 사항들 자세한 내용
- 7/22 모델링 리뷰 후, 수정사항 반영
- 제품에 대해 전체 카테고리 역할하는 Categories 테이블 생성
- 면도날 제품은 별도 속성이 없어, ManytoMany가 아니므로 단일로 생성(blade_products)
- 면도기(선물세트,면도기세트) 제품은 색상과 ManytoMany 관계이므로 colors 테이블과 ManytoMany로 생성(razor_products,razor_products_colors)
- 스킨제품(애프터쉐이브,쉐이빙젤) 제품은 사이즈와 ManytoMany 관계이므로 sizes 테이블과 ManytoMany로 생성(skin_products,skin_products_sizes)
- 장바구니 또는 결제내역에 담기는 사진은 order_images에 참조하는 테이블은 blade_products,razor_products_colors,skin_products_sizes

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-24 05:49 UTC, soheon-lee commented on products/models.py
> +    price       =   models.IntegerField()
가격은 `DecimalField`로 지정하는 것이 일반적입니다. 소숫점 아래 두번째 자리 혹은 네번째 자리 까지 포함할 수 있도록 수정해주세요.

2020-07-24 05:49 UTC, soheon-lee commented on products/models.py
> +    description =   models.CharField(max_length=50)
```suggestion
    name        = models.CharField(max_length=20)
    description = models.CharField(max_length=50)
```

2020-07-24 05:49 UTC, soheon-lee commented on products/models.py
> +    price       =   models.IntegerField()
```suggestion
    category    = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    name        = models.CharField(max_length=20)
    description = models.CharField(max_length=20,null=True)
    price       = models.IntegerField()
```

2020-07-24 06:04 UTC, soheon-lee commented on products/views.py
> +# Create your views here.
사용하지 않는 코드입니다. 제거해주세요.

2020-07-24 11:41 UTC, sincerity10 commented on products/models.py
> +    price       =   models.IntegerField()
수정하였습니다.

2020-07-24 11:43 UTC, sincerity10 commented on products/views.py
> +# Create your views here.
확인하고 수정하였습니다.

2020-07-24 11:44 UTC, sincerity10 commented on products/models.py
> +    price       =   models.IntegerField()
확인하고 수정하였습니다.

2020-07-24 11:44 UTC, sincerity10 commented on products/models.py
> +    description =   models.CharField(max_length=50)
확인하고 수정하였습니다.

2020-07-27 02:29 UTC, evergreen-david requested changes

2020-07-27 02:29 UTC, evergreen-david commented on wisely/urls.py
> +    #path('user',include('users.urls')),
주석은 정리를 부탁 드립니다.!

2020-07-27 02:29 UTC, evergreen-david commented on products/tests.py
> +from django.test import TestCase
ProductDetail , get에 대한 유닛 테스트 부탁 드립니다. 성공하는 대표 케이스 1개만 하면 됩니다.!

2020-07-27 13:07 UTC, sincerity10 commented on products/tests.py
> +from django.test import TestCase
확인하고 반영 했습니다.

2020-07-27 13:08 UTC, sincerity10 commented on wisely/urls.py
> +    #path('user',include('users.urls')),
반영했습니다.

2020-07-28 05:40 UTC, soheon-lee commented on products/views.py
> +from products.models    import Product,BladeProduct,ProductColor,ProductSize
```suggestion
from products.models    import (
    Product,
    BladeProduct,
    ProductColor,
    ProductSize
)
```
한 줄에서 여러 클래스를 import 할 때에는 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :)

2020-07-28 07:06 UTC, sincerity10 commented on products/views.py
> +from products.models    import Product,BladeProduct,ProductColor,ProductSize
확인 후 수정하였습니다.

2020-07-28 08:27 UTC, soheon-lee commented on products/views.py
> +            product = Product.objects.get(id=product_id)
get method를 사용하기 전에 filter( )메소드와 exist( ) 메소드를 이용하여 해당 상품이 존재하는 지 여부를 검사하시는 것이 좋습니다.

2020-07-28 08:27 UTC, soheon-lee commented on products/views.py
> +            if product_id >= 1 and product_id < 3:
`product_id`에 따라 하드코딩 되어 있습니다. 제품의 카테고리 테이블을 추가하시고, 해당 카테고리에 따라 어떤 제품의 특성을 표출할 지 결정해보는 것을 추천드립니다.

2020-07-29 02:03 UTC, sincerity10 commented on products/views.py
> +            if product_id >= 1 and product_id < 3:
if를 하나로 줄이려고 했는데 category에 따라 가격정보를 불러오는 테이블이 달라 어쩔 수 없이 3개로 밖에 되지 않는 것 같습니다.
price 정보가 별도 ManyToMany(Color 옵션과 Product,Size 옵션과 Product, No Option과 Product)관계로 형성된 테이블의 컬럼이라서요.

2020-07-29 02:03 UTC, sincerity10 commented on products/views.py
> +            product = Product.objects.get(id=product_id)
추가 했는데 확인해보겠습니다.

2020-07-29 04:00 UTC, evergreen-david requested changes

2020-07-29 04:00 UTC, evergreen-david commented on products/views.py
> +            if category_id == 1:
매직넘버 1을 어떤 카테고리의 상수로 만들어 주시겠어요 ?
예를들어, 1이 RAZOR 라면 클래스 변수로 RAZOR = 1 이런식으로 해서 사용하면 가독성이 좋아집니다.
숫자 1이란 카테고리는 코드작성한 개발자만 알 수 있으므로.

2020-07-29 06:45 UTC, sincerity10 commented on products/views.py
> +            if category_id == 1:
리뷰 정말 감사합니다!
그 방법은 생각을 못 했었네요.
수정 했습니다.

2020-07-30 02:23 UTC, soheon-lee commented
LGTM

2020-07-30 02:23 UTC, merged