[황수미] Add: 프론트와 붙여보기 성공
wecode-bootcamp-korea/10-RonWesely-backend pull request #4
Opened 2020-07-23 02:40 UTC by ifyouseeksoomi

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
회원가입, 로그인 엔드포인트 구현         
		 
## 수정 사항들 자세한 내용
첫 PR이라 아직 수정 사항 없습니다.
앞으로 수정할 내용:
- models.py 컬럼명 변경(데이터 모델링 리뷰 세션 참고)
- 회원가입 views.py 로직 수정(생일 숫자로 들어가지 않으면 가입 불가하도록, 회원 가입 시 바로 토큰 생성하여 넘겨주어 가입과 동시에 로그인될 수 있도록)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ? ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-24 02:44 UTC, soheon-lee commented on users/models.py
> +    modified_at = models.DateTimeField(auto_now = True)
코드 간격 `=`을 기준으로 정렬해주세요.

2020-07-24 02:44 UTC, soheon-lee commented on users/models.py
> +    path_lists = models.ForeignKey('Path', on_delete=models.SET_NULL, null=True)
코드 간격 =을 기준으로 정렬해주세요.

2020-07-24 02:44 UTC, soheon-lee commented on users/models.py
> +    is_default = models.BooleanField()
코드 간격 =을 기준으로 정렬해주세요.

2020-07-24 02:44 UTC, soheon-lee commented on users/models.py
> +
불필요한 공백은 모두 제거해주세요

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +
사용하지 않는 코드입니다. 제거해주세요

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +from .models import Users, Gender
```suggestion
from django.views import View
from django.http import JsonResponse

import my_settings
from .models import (
    Users, 
    Gender
)
```

한 줄에서 import 하고자 하는 대상이 두 개 이상일 경우 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :-)

2020-07-24 02:44 UTC, soheon-lee commented on users/tests.py
> +# Create your tests here.
불필요한 공백 및 주석 정리해주세요 :)

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +            return JsonResponse({'name':user_name_s}, safe=False)
이 뷰의 역할은 무엇일까요? 로그인과는 별개인가요?

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +                    token = jwt.encode({'email':data['email']}, my_settings.SECRET_KEY['secret'], algorithm="HS256")
토큰에 `email`등 개인 정보가 담기는 것은 보안에 취약합니다. 이메일을 바로 담기보단, email을 가지고 확인한 user 객체의 고유한 `id`를 담으시는 것을 추천드립니다 :) 91번 줄에서 user 객체를 get 해오셨으니, 그 객체의 id를 어떻게 담을 수 있을까요?

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +                user= Users.objects.get(email=data['email'])
```suggestion
                user = Users.objects.get(email=data['email'])
```

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +                    return JsonResponse({'Profile':{'name':user.name, 'email':user.email}}, status=200, safe=False)
로그인을 하면 `token`을 return 해주어야 합니다. 이름과 이메일등의 개인 정보는 암호화 하지 않은 상태로 전달하지 않습니다.

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +            return JsonResponse({'Message':'Key_error'}, status=400)
```suggestion
        except KeyError:
            return JsonResponse({'Message':'KEY_ERROR'}, status=400)
```
에러메세지는 통상적으로 모두 대문자, 간격은 언더바(_)로 구분합니다 :) 스타일 통일해주세요~

2020-07-24 02:44 UTC, soheon-lee commented on users/views.py
> +                    token = jwt.encode({'email':data['email']}, my_settings.SECRET_KEY['secret'], algorithm="HS256")
토큰을 암호화하는 알고리즘이 외부에 노출되었습니다. SECRET_KEY와 마찬가지로 ALGORITHM또한 git에 업로드하지 않는 외부 숨김 파일에 분리해주세요.

2020-07-24 02:44 UTC, soheon-lee commented on wisely/urls.py
> +from django.urls import include, path
한 줄에서 import 하고자 하는 대상이 두 개 이상일 경우 개별 줄로 분리해주는 것이 위코드 코딩 컨벤션입니다 :-)

2020-07-24 02:44 UTC, soheon-lee commented on wisely/urls.py
> +#from django.contrib import admin
사용하지 않는 주석은 제거해주세요

2020-07-24 02:50 UTC, ifyouseeksoomi commented on users/models.py
> +    modified_at = models.DateTimeField(auto_now = True)
넵!

2020-07-24 02:51 UTC, ifyouseeksoomi commented on users/models.py
> +    path_lists = models.ForeignKey('Path', on_delete=models.SET_NULL, null=True)
넵!

2020-07-24 02:52 UTC, ifyouseeksoomi commented on users/models.py
> +    is_default = models.BooleanField()
넵!

2020-07-24 02:52 UTC, ifyouseeksoomi commented on users/models.py
> +
넵~!

2020-07-24 02:55 UTC, ifyouseeksoomi commented on users/views.py
> +                    return JsonResponse({'Profile':{'name':user.name, 'email':user.email}}, status=200, safe=False)
근데 와이즐리 홈페이지 같은 경우, 로그인 시 "안녕하세요 황수미님"과 함께 제 이메일주소를 보여줍니다. 토큰과 함께 이름과 이메일 리턴하면 될까요?
<img width="1041" alt="스크린샷 2020-07-24 오전 11 54 47" src="https://user-images.githubusercontent.com/59601700/88356942-7b964e00-cda4-11ea-85c7-d51518c8277f.png">

2020-07-24 02:55 UTC, ifyouseeksoomi commented on users/views.py
> +
넵!

2020-07-24 02:56 UTC, ifyouseeksoomi commented on users/views.py
> +            return JsonResponse({'Message':'Key_error'}, status=400)
넵!

2020-07-24 03:02 UTC, ifyouseeksoomi commented on users/views.py
> +                    token = jwt.encode({'email':data['email']}, my_settings.SECRET_KEY['secret'], algorithm="HS256")
넵~!

2020-07-24 03:03 UTC, ifyouseeksoomi commented on wisely/urls.py
> +#from django.contrib import admin
넵!

2020-07-24 03:03 UTC, ifyouseeksoomi commented on wisely/urls.py
> +from django.urls import include, path
냅~!

2020-07-24 04:37 UTC, ifyouseeksoomi commented on users/views.py
> +                    return JsonResponse({'Profile':{'name':user.name, 'email':user.email}}, status=200, safe=False)
곤호님과 상의 결과 이 단계에서는 토큰만 주는게 맞다고 판단하여 우선 토큰만 리턴하는 것으로 수정했습니다.

2020-07-24 06:42 UTC, evergreen-david requested changes

2020-07-24 06:42 UTC, evergreen-david commented on users/views.py
> +#        return JsonResponse ({"message":"no user"}, status=400)
주석 정리 부탁 드립니다.

2020-07-24 06:42 UTC, evergreen-david commented on users/views.py
> +            #    return JsonResponse({'message':'invalid_birthday'}, status=400)
주석 정리 부탁 드립니다.

2020-07-24 06:42 UTC, evergreen-david commented on users/views.py
> +class SignIn_when_email_exists(View):
클래스명은 소문자로 하지 않고 카멜케이스로 수정 부탁 드립니다.

2020-07-25 04:49 UTC, ifyouseeksoomi commented on users/views.py
> +#        return JsonResponse ({"message":"no user"}, status=400)
넵~!

2020-07-25 04:50 UTC, ifyouseeksoomi commented on users/views.py
> +            #    return JsonResponse({'message':'invalid_birthday'}, status=400)
넵~!

2020-07-25 04:50 UTC, ifyouseeksoomi commented on users/views.py
> +class SignIn_when_email_exists(View):
수정하였습니다~!

2020-07-27 02:32 UTC, evergreen-david requested changes

2020-07-27 02:32 UTC, evergreen-david commented on users/models.py
> +
클래스간 간격은 한줄로 부탁 드리겠습니다.

2020-07-27 02:32 UTC, evergreen-david commented on users/models.py
> +    email        = models.CharField(max_length=250)
```suggestion
    email        = models.EmailField(max_length=250)
```

2020-07-27 02:32 UTC, evergreen-david commented on users/models.py
> +
클래스간 간격에 대한 같은 커멘트 입니다.

2020-07-27 02:32 UTC, evergreen-david commented on users/models.py
> +
클래스간 간격에 대한 같은 커멘트 입니다.

2020-07-27 02:32 UTC, evergreen-david commented on users/models.py
> +
클래스간 간격에 대한 같은 커멘트 입니다.

2020-07-27 02:32 UTC, evergreen-david commented on users/tests.py
> +#        Users.objects.create(
주석은 남기지 말고 정리 부탁 드립니다.

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/tests.py
> +#        Users.objects.create(
아직 tests.py를 마무리하지 못하여 계속해서 고치는 중인데 다 고친 후에 지워도 괜찮을까요?

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/models.py
> +
정리하였습니다!

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/models.py
> +
정리하였습니다!

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/models.py
> +
정리하였습니다!

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/models.py
> +    email        = models.CharField(max_length=250)
바꾸었습니다.

2020-07-27 05:46 UTC, ifyouseeksoomi commented on users/models.py
> +
정리하였습니다!

2020-07-30 11:40 UTC, merged